{ config, pkgs, osConfig, ... }:

let
  vars = import ./vars.nix;
in
{
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = "demivan";
  home.homeDirectory = "/home/demivan";

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "23.11"; # Please read the comment before changing.

  nixpkgs.config.allowUnfree = true;

  fonts.fontconfig.enable = true;

  # The home.packages option allows you to install Nix packages into your
  # environment.
  home.packages = with pkgs; [
    # Looks
    rofi
    wofi
    fish
    waybar
    (nerdfonts.override { fonts = [ vars.font ]; })

    # General
    firefox-devedition

    # Development
    git
    vscodium

    # Communication
    slack
    telegram-desktop
  ];

  xdg.configFile = {
    "fontconfig/conf.d/52-hm-default-fonts.conf".text = let
      genDefault = fonts: name:
        pkgs.lib.optionalString (fonts != [ ]) ''
          <alias binding="same">
            <family>${name}</family>
            <prefer>
            ${
              pkgs.lib.concatStringsSep "" (map (font: ''
                <family>${font}</family>
              '') fonts)
            }
            </prefer>
          </alias>
        '';
    in ''
      <?xml version='1.0'?>

      <!-- Generated by Home Manager. -->

      <!DOCTYPE fontconfig SYSTEM 'urn:fontconfig:fonts.dtd'>
      <fontconfig>
        <!-- Default fonts -->
        ${genDefault vars.defaultFonts.sansSerif "sans-serif"}
        ${genDefault vars.defaultFonts.serif "serif"}
        ${genDefault vars.defaultFonts.monospace "monospace"}
        ${genDefault vars.defaultFonts.emoji "emoji"}
      </fontconfig>
    '';
  };

  # Home Manager is pretty good at managing dotfiles. The primary way to manage
  # plain files is through 'home.file'.
  home.file = {
    # # Building this configuration will create a copy of 'dotfiles/screenrc' in
    # # the Nix store. Activating the configuration will then make '~/.screenrc' a
    # # symlink to the Nix store copy.
    # ".screenrc".source = dotfiles/screenrc;

    # # You can also set the file content immediately.
    # ".gradle/gradle.properties".text = ''
    #   org.gradle.console=verbose
    #   org.gradle.daemon.idletimeout=3600000
    # '';
  };

  # Home Manager can also manage your environment variables through
  # 'home.sessionVariables'.
  home.sessionVariables = {
    NIXOS_OZONE_WL = "1";
    # EDITOR = "emacs";
  };

  # Let Home Manager install and manage itself.
  programs.home-manager = {
    enable = true;
  };

  # UI
  services.mako = {
    enable = true;
    defaultTimeout = 5000;
  };

  # Shell

  programs.fish = {
    enable = true;
  };

  programs.kitty = {
    enable = true;
    theme = "Catppuccin-Mocha";
    settings = {
      font_size = 13;
      window_padding_width = 4;
    };
    shellIntegration.enableFishIntegration = true;
  };

  programs.starship = {
    enable = true;
    settings = {
      add_newline = false;
    };
  };

  # Theme
  gtk = {
    enable = true;
    theme = {
      name = "Catppuccin-Mocha-Compact-Blue-Dark";
      package = pkgs.catppuccin-gtk.override {
        accents = [ "blue" ];
        size = "compact";
        tweaks = [ "rimless" ];
        variant = "mocha";
      };
    };
  };
}
